apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: calculator-app
        image: your-docker-registry/calculator-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
  namespace: dev
spec:
  selector:
    app: calculator-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort

