stages:
  - build
  - push
  - deploy

variables:
  DOCKER_IMAGE: "your-docker-registry/calculator-app"
  K8S_NAMESPACE: "dev"
  K8S_DEPLOYMENT_NAME: "calculator-app"

before_script:
  # Use Docker-in-Docker to build and push images
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD your-docker-registry

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHA $DOCKER_IMAGE:latest

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
    - docker push $DOCKER_IMAGE:latest

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl config use-context minikube
    - kubectl create namespace $K8S_NAMESPACE || echo "Namespace $K8S_NAMESPACE already exists"
    - kubectl apply -f k8s-deployment.yml -n $K8S_NAMESPACE

